// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fileheaders

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRun_SkipGenerated(t *testing.T) {
	tmpDir := t.TempDir()

	// Create config
	configDir := filepath.Join(tmpDir, ".codestyle")
	if err := os.MkdirAll(configDir, 0755); err != nil {
		t.Fatal(err)
	}
	configFile := filepath.Join(configDir, "file-headers.yaml")
	// We explicitly set skipGenerated to true, although we plan to make it default.
	configContent := `
license: apache-2.0
copyrightHolder: Google LLC
skipGenerated: true
`
	if err := os.WriteFile(configFile, []byte(configContent), 0644); err != nil {
		t.Fatal(err)
	}

	// Create a generated go file
	genFile := filepath.Join(tmpDir, "generated.go")
	genContent := `// Code generated by controller-gen. DO NOT EDIT.
package main

func main() {}
`
	if err := os.WriteFile(genFile, []byte(genContent), 0644); err != nil {
		t.Fatal(err)
	}

	// Create a normal go file
	normalFile := filepath.Join(tmpDir, "normal.go")
	normalContent := `package main

func main() {}
`
	if err := os.WriteFile(normalFile, []byte(normalContent), 0644); err != nil {
		t.Fatal(err)
	}

	// Run fileheaders
	ctx := context.Background()
	if err := Run(ctx, tmpDir, nil); err != nil {
		t.Fatalf("Run failed: %v", err)
	}

	// Verify generated file was NOT modified
	content, err := os.ReadFile(genFile)
	if err != nil {
		t.Fatal(err)
	}
	if string(content) != genContent {
		t.Errorf("Generated file was modified but should have been skipped. Content:\n%s", string(content))
	}

	// Verify normal file WAS modified
	content, err = os.ReadFile(normalFile)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(content), "Copyright") {
		t.Errorf("Normal file was NOT modified but should have been. Content:\n%s", string(content))
	}
}

func TestRun_SkipGenerated_Default(t *testing.T) {
	tmpDir := t.TempDir()

	// Create config WITHOUT skipGenerated
	configDir := filepath.Join(tmpDir, ".codestyle")
	if err := os.MkdirAll(configDir, 0755); err != nil {
		t.Fatal(err)
	}
	configFile := filepath.Join(configDir, "file-headers.yaml")
	configContent := `
license: apache-2.0
copyrightHolder: Google LLC
`
	if err := os.WriteFile(configFile, []byte(configContent), 0644); err != nil {
		t.Fatal(err)
	}

	// Create a generated go file
	genFile := filepath.Join(tmpDir, "generated.go")
	genContent := `// Code generated by controller-gen. DO NOT EDIT.
package main

func main() {}
`
	if err := os.WriteFile(genFile, []byte(genContent), 0644); err != nil {
		t.Fatal(err)
	}

	// Run fileheaders
	ctx := context.Background()
	if err := Run(ctx, tmpDir, nil); err != nil {
		t.Fatalf("Run failed: %v", err)
	}

	// Verify generated file was NOT modified
	content, err := os.ReadFile(genFile)
	if err != nil {
		t.Fatal(err)
	}
	if string(content) != genContent {
		t.Errorf("Generated file was modified but should have been skipped by default. Content:\n%s", string(content))
	}
}

func TestRun_SkipGenerated_False(t *testing.T) {
	tmpDir := t.TempDir()

	// Create config with skipGenerated: false
	configDir := filepath.Join(tmpDir, ".codestyle")
	if err := os.MkdirAll(configDir, 0755); err != nil {
		t.Fatal(err)
	}
	configFile := filepath.Join(configDir, "file-headers.yaml")
	configContent := `
license: apache-2.0
copyrightHolder: Google LLC
skipGenerated: false
`
	if err := os.WriteFile(configFile, []byte(configContent), 0644); err != nil {
		t.Fatal(err)
	}

	// Create a generated go file
	genFile := filepath.Join(tmpDir, "generated.go")
	genContent := `// Code generated by controller-gen. DO NOT EDIT.
package main

func main() {}
`
	if err := os.WriteFile(genFile, []byte(genContent), 0644); err != nil {
		t.Fatal(err)
	}

	// Run fileheaders
	ctx := context.Background()
	if err := Run(ctx, tmpDir, nil); err != nil {
		t.Fatalf("Run failed: %v", err)
	}

	// Verify generated file WAS modified
	content, err := os.ReadFile(genFile)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(content), "Copyright") {
		t.Errorf("Generated file was NOT modified but should have been (skipGenerated: false). Content:\n%s", string(content))
	}
}
