// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package fileset

import (
	"go/parser"
	"go/token"
	"testing"

	"golang.org/x/tools/go/analysis"
)

func TestIsGenerated(t *testing.T) {
	tests := []struct {
		name     string
		src      string
		expected bool
	}{
		{
			name:     "standard controller-gen header",
			src:      "// Code generated by controller-gen. DO NOT EDIT.\npackage main\n",
			expected: true,
		},
		{
			name:     "standard protoc header",
			src:      "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage main\n",
			expected: true,
		},
		{
			name:     "multiline comments with generated",
			src:      "// Some comment\n// Code generated by tool. DO NOT EDIT.\npackage main\n",
			expected: true,
		},
		{
			name:     "handwritten code",
			src:      "// Package main implements something.\npackage main\n",
			expected: false,
		},
		{
			name:     "incomplete comment without DO NOT EDIT",
			src:      "// Code generated by hand.\npackage main\n",
			expected: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			fset := token.NewFileSet()
			file, err := parser.ParseFile(fset, "test.go", tt.src, parser.ParseComments)
			if err != nil {
				t.Fatalf("ParseFile failed: %v", err)
			}
			got := IsGenerated(file)
			if got != tt.expected {
				t.Errorf("IsGenerated() = %v, want %v", got, tt.expected)
			}
		})
	}
}

func TestIsTest(t *testing.T) {
	if !IsTest("foo_test.go") {
		t.Errorf("expected foo_test.go to be a test file")
	}
	if !IsTest("/path/to/bar_test.go") {
		t.Errorf("expected /path/to/bar_test.go to be a test file")
	}
	if IsTest("foo.go") {
		t.Errorf("expected foo.go to not be a test file")
	}
	if IsTest("test.go") {
		t.Errorf("expected test.go to not be a test file")
	}
}

func TestIsVendored(t *testing.T) {
	if !IsVendored("vendor/github.com/pkg/errors/errors.go") {
		t.Errorf("expected vendor/... to be vendored")
	}
	if !IsVendored("pkg/vendor/foo.go") {
		t.Errorf("expected pkg/vendor/... to be vendored")
	}
	if IsVendored("vendor-tools/bar.go") {
		t.Errorf("vendor-tools/bar.go should not be vendored")
	}
	if IsVendored("pkg/vendoring/foo.go") {
		t.Errorf("pkg/vendoring/foo.go should not be vendored")
	}
	if IsVendored("pkg/normal.go") {
		t.Errorf("pkg/normal.go should not be vendored")
	}
}

func TestPolicy_ShouldSkip(t *testing.T) {
	fset := token.NewFileSet()
	genFile, err := parser.ParseFile(fset, "gen.go", "// Code generated by tool. DO NOT EDIT.\npackage p\n", parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}
	normalFile, err := parser.ParseFile(fset, "normal.go", "package p\n", parser.ParseComments)
	if err != nil {
		t.Fatal(err)
	}

	// 1. SkipGenerated: false
	pNoSkipGen := NewPolicy(false, false, nil, "")
	if pNoSkipGen.ShouldSkip("gen.go", genFile) {
		t.Errorf("expected generated file to NOT be skipped when SkipGenerated is false")
	}
	if pNoSkipGen.ShouldSkip("normal.go", normalFile) {
		t.Errorf("expected normal file to NOT be skipped")
	}

	// 2. SkipGenerated: true
	pSkipGen := NewPolicy(true, false, nil, "")
	if !pSkipGen.ShouldSkip("gen.go", genFile) {
		t.Errorf("expected generated file to be skipped when SkipGenerated is true")
	}
	if pSkipGen.ShouldSkip("normal.go", normalFile) {
		t.Errorf("expected normal file to NOT be skipped when SkipGenerated is true")
	}

	// 3. SkipTests: true vs false
	pSkipTests := NewPolicy(false, true, nil, "")
	if !pSkipTests.ShouldSkip("foo_test.go", nil) {
		t.Errorf("expected test file to be skipped when SkipTests is true")
	}
	pNoSkipTests := NewPolicy(false, false, nil, "")
	if pNoSkipTests.ShouldSkip("foo_test.go", nil) {
		t.Errorf("expected test file to NOT be skipped when SkipTests is false")
	}

	// 4. SkipVendored: true
	pSkipVendored := NewPolicy(false, false, nil, "/repo")
	if !pSkipVendored.ShouldSkip("/repo/vendor/lib/x.go", nil) {
		t.Errorf("expected vendor file to be skipped when SkipVendored is true")
	}
	if pSkipVendored.ShouldSkip("/repo/vendor-tools/x.go", nil) {
		t.Errorf("expected vendor-tools file to NOT be skipped")
	}

	// 5. SkipGlobs
	pSkipGlobs := NewPolicy(false, false, []string{"testdata/**", "*.ignore.go"}, "/repo")
	if !pSkipGlobs.ShouldSkip("/repo/testdata/sub/a.go", nil) {
		t.Errorf("expected /repo/testdata/sub/a.go to be skipped by glob")
	}
	if !pSkipGlobs.ShouldSkip("/repo/pkg/foo.ignore.go", nil) {
		t.Errorf("expected /repo/pkg/foo.ignore.go to be skipped by glob")
	}
	if pSkipGlobs.ShouldSkip("/repo/pkg/bar.go", nil) {
		t.Errorf("expected /repo/pkg/bar.go to NOT be skipped")
	}
}

func TestRegisterFlags(t *testing.T) {
	analyzer := &analysis.Analyzer{
		Name: "testcheck",
	}
	flags := RegisterFlags(analyzer, false, true)

	pDefault := flags.NewPolicy()
	if pDefault.SkipGenerated {
		t.Errorf("expected default SkipGenerated to be false")
	}
	if !pDefault.SkipTests {
		t.Errorf("expected default SkipTests to be true")
	}

	if err := analyzer.Flags.Set("skip-generated", "true"); err != nil {
		t.Fatal(err)
	}
	if err := analyzer.Flags.Set("skip-tests", "false"); err != nil {
		t.Fatal(err)
	}
	if err := analyzer.Flags.Set("skip-glob", "gen/**,auto/**"); err != nil {
		t.Fatal(err)
	}
	if err := analyzer.Flags.Set("repo-root", "/my/repo"); err != nil {
		t.Fatal(err)
	}

	pUpdated := flags.NewPolicy()
	if !pUpdated.SkipGenerated {
		t.Errorf("expected SkipGenerated to be true after flag set")
	}
	if pUpdated.SkipTests {
		t.Errorf("expected SkipTests to be false after flag set")
	}
	if len(pUpdated.SkipGlobs) != 2 || pUpdated.SkipGlobs[0] != "gen/**" || pUpdated.SkipGlobs[1] != "auto/**" {
		t.Errorf("unexpected SkipGlobs: %v", pUpdated.SkipGlobs)
	}
	if pUpdated.RepoRoot != "/my/repo" {
		t.Errorf("expected RepoRoot to be /my/repo, got %q", pUpdated.RepoRoot)
	}
}
