// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: ap/pkg/sandbox/api/ap.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileRequest) Reset() {
	*x = WriteFileRequest{}
	mi := &file_ap_pkg_sandbox_api_ap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileRequest) ProtoMessage() {}

func (x *WriteFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ap_pkg_sandbox_api_ap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileRequest.ProtoReflect.Descriptor instead.
func (*WriteFileRequest) Descriptor() ([]byte, []int) {
	return file_ap_pkg_sandbox_api_ap_proto_rawDescGZIP(), []int{0}
}

func (x *WriteFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteFileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type WriteFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteFileResponse) Reset() {
	*x = WriteFileResponse{}
	mi := &file_ap_pkg_sandbox_api_ap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteFileResponse) ProtoMessage() {}

func (x *WriteFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ap_pkg_sandbox_api_ap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteFileResponse.ProtoReflect.Descriptor instead.
func (*WriteFileResponse) Descriptor() ([]byte, []int) {
	return file_ap_pkg_sandbox_api_ap_proto_rawDescGZIP(), []int{1}
}

type ReadFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileRequest) Reset() {
	*x = ReadFileRequest{}
	mi := &file_ap_pkg_sandbox_api_ap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileRequest) ProtoMessage() {}

func (x *ReadFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ap_pkg_sandbox_api_ap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileRequest.ProtoReflect.Descriptor instead.
func (*ReadFileRequest) Descriptor() ([]byte, []int) {
	return file_ap_pkg_sandbox_api_ap_proto_rawDescGZIP(), []int{2}
}

func (x *ReadFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       []byte                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadFileResponse) Reset() {
	*x = ReadFileResponse{}
	mi := &file_ap_pkg_sandbox_api_ap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadFileResponse) ProtoMessage() {}

func (x *ReadFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ap_pkg_sandbox_api_ap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadFileResponse.ProtoReflect.Descriptor instead.
func (*ReadFileResponse) Descriptor() ([]byte, []int) {
	return file_ap_pkg_sandbox_api_ap_proto_rawDescGZIP(), []int{3}
}

func (x *ReadFileResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type RunTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []string               `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTaskRequest) Reset() {
	*x = RunTaskRequest{}
	mi := &file_ap_pkg_sandbox_api_ap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTaskRequest) ProtoMessage() {}

func (x *RunTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ap_pkg_sandbox_api_ap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTaskRequest.ProtoReflect.Descriptor instead.
func (*RunTaskRequest) Descriptor() ([]byte, []int) {
	return file_ap_pkg_sandbox_api_ap_proto_rawDescGZIP(), []int{4}
}

func (x *RunTaskRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

type RunTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Stdout        string                 `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        string                 `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	ChangedFiles  []*ChangedFile         `protobuf:"bytes,4,rep,name=changed_files,json=changedFiles,proto3" json:"changed_files,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTaskResponse) Reset() {
	*x = RunTaskResponse{}
	mi := &file_ap_pkg_sandbox_api_ap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTaskResponse) ProtoMessage() {}

func (x *RunTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ap_pkg_sandbox_api_ap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTaskResponse.ProtoReflect.Descriptor instead.
func (*RunTaskResponse) Descriptor() ([]byte, []int) {
	return file_ap_pkg_sandbox_api_ap_proto_rawDescGZIP(), []int{5}
}

func (x *RunTaskResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RunTaskResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *RunTaskResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *RunTaskResponse) GetChangedFiles() []*ChangedFile {
	if x != nil {
		return x.ChangedFiles
	}
	return nil
}

type ChangedFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangedFile) Reset() {
	*x = ChangedFile{}
	mi := &file_ap_pkg_sandbox_api_ap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangedFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangedFile) ProtoMessage() {}

func (x *ChangedFile) ProtoReflect() protoreflect.Message {
	mi := &file_ap_pkg_sandbox_api_ap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangedFile.ProtoReflect.Descriptor instead.
func (*ChangedFile) Descriptor() ([]byte, []int) {
	return file_ap_pkg_sandbox_api_ap_proto_rawDescGZIP(), []int{6}
}

func (x *ChangedFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ChangedFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

var File_ap_pkg_sandbox_api_ap_proto protoreflect.FileDescriptor

const file_ap_pkg_sandbox_api_ap_proto_rawDesc = "" +
	"\n" +
	"\x1bap/pkg/sandbox/api/ap.proto\x12\rap.sandbox.v1\"@\n" +
	"\x10WriteFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\x13\n" +
	"\x11WriteFileResponse\"%\n" +
	"\x0fReadFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\",\n" +
	"\x10ReadFileResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\fR\acontent\"$\n" +
	"\x0eRunTaskRequest\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\"\x9f\x01\n" +
	"\x0fRunTaskResponse\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\tR\x06stderr\x12?\n" +
	"\rchanged_files\x18\x04 \x03(\v2\x1a.ap.sandbox.v1.ChangedFileR\fchangedFiles\";\n" +
	"\vChangedFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent2\xf7\x01\n" +
	"\x0eSandboxService\x12N\n" +
	"\tWriteFile\x12\x1f.ap.sandbox.v1.WriteFileRequest\x1a .ap.sandbox.v1.WriteFileResponse\x12K\n" +
	"\bReadFile\x12\x1e.ap.sandbox.v1.ReadFileRequest\x1a\x1f.ap.sandbox.v1.ReadFileResponse\x12H\n" +
	"\aRunTask\x12\x1d.ap.sandbox.v1.RunTaskRequest\x1a\x1e.ap.sandbox.v1.RunTaskResponseB7Z5github.com/gke-labs/gke-labs-infra/ap/pkg/sandbox/apib\x06proto3"

var (
	file_ap_pkg_sandbox_api_ap_proto_rawDescOnce sync.Once
	file_ap_pkg_sandbox_api_ap_proto_rawDescData []byte
)

func file_ap_pkg_sandbox_api_ap_proto_rawDescGZIP() []byte {
	file_ap_pkg_sandbox_api_ap_proto_rawDescOnce.Do(func() {
		file_ap_pkg_sandbox_api_ap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ap_pkg_sandbox_api_ap_proto_rawDesc), len(file_ap_pkg_sandbox_api_ap_proto_rawDesc)))
	})
	return file_ap_pkg_sandbox_api_ap_proto_rawDescData
}

var file_ap_pkg_sandbox_api_ap_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ap_pkg_sandbox_api_ap_proto_goTypes = []any{
	(*WriteFileRequest)(nil),  // 0: ap.sandbox.v1.WriteFileRequest
	(*WriteFileResponse)(nil), // 1: ap.sandbox.v1.WriteFileResponse
	(*ReadFileRequest)(nil),   // 2: ap.sandbox.v1.ReadFileRequest
	(*ReadFileResponse)(nil),  // 3: ap.sandbox.v1.ReadFileResponse
	(*RunTaskRequest)(nil),    // 4: ap.sandbox.v1.RunTaskRequest
	(*RunTaskResponse)(nil),   // 5: ap.sandbox.v1.RunTaskResponse
	(*ChangedFile)(nil),       // 6: ap.sandbox.v1.ChangedFile
}
var file_ap_pkg_sandbox_api_ap_proto_depIdxs = []int32{
	6, // 0: ap.sandbox.v1.RunTaskResponse.changed_files:type_name -> ap.sandbox.v1.ChangedFile
	0, // 1: ap.sandbox.v1.SandboxService.WriteFile:input_type -> ap.sandbox.v1.WriteFileRequest
	2, // 2: ap.sandbox.v1.SandboxService.ReadFile:input_type -> ap.sandbox.v1.ReadFileRequest
	4, // 3: ap.sandbox.v1.SandboxService.RunTask:input_type -> ap.sandbox.v1.RunTaskRequest
	1, // 4: ap.sandbox.v1.SandboxService.WriteFile:output_type -> ap.sandbox.v1.WriteFileResponse
	3, // 5: ap.sandbox.v1.SandboxService.ReadFile:output_type -> ap.sandbox.v1.ReadFileResponse
	5, // 6: ap.sandbox.v1.SandboxService.RunTask:output_type -> ap.sandbox.v1.RunTaskResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_ap_pkg_sandbox_api_ap_proto_init() }
func file_ap_pkg_sandbox_api_ap_proto_init() {
	if File_ap_pkg_sandbox_api_ap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ap_pkg_sandbox_api_ap_proto_rawDesc), len(file_ap_pkg_sandbox_api_ap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ap_pkg_sandbox_api_ap_proto_goTypes,
		DependencyIndexes: file_ap_pkg_sandbox_api_ap_proto_depIdxs,
		MessageInfos:      file_ap_pkg_sandbox_api_ap_proto_msgTypes,
	}.Build()
	File_ap_pkg_sandbox_api_ap_proto = out.File
	file_ap_pkg_sandbox_api_ap_proto_goTypes = nil
	file_ap_pkg_sandbox_api_ap_proto_depIdxs = nil
}
